### ISSUE TITLE
Can't center grid columns in small/medium device-widths

### ISSUE THREAD

**Issue by tombyers** [daneden/Toast#53]
I want to center a `.grid__col--m-2-of-3` column. But it looks like this selector:

```css
@media (max-width: $toast-breakpoint-medium) and (min-width: $toast-breakpoint-small) {
  &[class*="#{$toast-grid-column-namespace}--m-"] {
    display: inline-block;
    margin-right: -.24em;
  }
   ... 
}
```
is overriding the `display:block; margin-right:auto;` of `.grid__col--centered`. Hence I can't center the column. 

Inspector screenshot below:

![screen shot 2017-02-01 at 10 10 15](https://cloud.githubusercontent.com/assets/16062922/22502838/ac6c12e8-e866-11e6-9c08-2bb19dfb3c00.png)

Is this a bug or am I missing something? Why is the `display:inline-block` selector necessary? Surely these declarations are by default inherited from `.grid__col` anyhow?

Thanks
